name: Build, Test, Deploy Docs

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  Documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install -U sphinx
          pipenv install sphinx-rtd-theme

      - name: Build
        run: |
          pipenv run make clean
          pipenv run make html
        working-directory: docs
      
      - name: Vale Tests
        uses: errata-ai/vale-action@v1.3.0
        with:
          config: https://raw.githubusercontent.com/errata-ai/vale/master/.vale.ini
          files: ../../docs/build/html
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master 
          FOLDER: docs/build
          CLEAN: true 
          
          
          
          
          
