

name: Build, Test, Deploy Docs

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
  
      - name: Install
        run: |
          pip install -U pip
          pip install pipenv
          pipenv install # set up the environment
          curl -sfL https://install.goreleaser.com/github.com/ValeLint/vale.sh | sh -s v2.1.0 # install vale
          export PATH="./bin:$PATH"
          
      - name: Build and Test
        run: |
          pipenv run make html
          vale --minAlertLevel error source
          
      - name: Deploy
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          BRANCH: master # The branch the action should deploy to.
          FOLDER: docs/build # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          
          
          
          
          
